name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 30.2
      - name: Install package dependencies
        run: make install-deps
      - name: Run tests
        run: make test
      - name: Byte-compile
        run: make build
